# Data {#appendixdata}

This section includes brief explanations of the various datasets we will be using in this book.

## hcandersenr 

The **hcandersenr**[@R-hcandersenr] package includes the text of the 157 known fairy tales by the Danish author H.C. Andersen. 
The text comes with 5 different languages with 

- 156 in English,
- 154 in Spanish,
- 150 in German,
- 138 in Danish and
- 58 in French

The package comes with a dataset for each language with the naming convention `hcandersen_**`,
where `**` is a country code.
Each dataset comes as a data.frame with two columns; `text` and `book` where the `book` variable has the text divided into strings of up to 80 characters.

The package also comes with a dataset called `EK` which includes information about the publication date, language of origin and names in the different languages.

## US Consumer Finance Complaints 

This [dataset](https://www.kaggle.com/cfpb/us-consumer-finance-complaints) includes 117214 consumers’ complaints about financial products and services to companies for response. Each comes with a `complaint_id`, various categorical variables and a text column `consumer_complaint_narrative` containing the written complaints.

## Opinions of the Supreme Court of the United States 

The **scotus** [@R-scotus] package contains a sample of the Supreme Court of the United States' opinions.
The `scotus_sample` data.frame includes 1 opinion per row along with the year, case name, docket number, and a unique ID number.

The text has had minimal preprocessing done on them and will include the header information in the text field.
Example of the beginning of a court opinion is shown below
 
```{r, echo=FALSE}
library(scotus)
cat(paste(stringr::str_wrap(head(strsplit(scotus_sample$text[42], "\n")[[1]])), collapse = "\n"))
```

## Kickstarter campaign blurbs

This dataset includes tktk...

