# Preface {#intro}

## Outline

The book is divided into three sections. We make a (perhaps arbitrary) distinction between *machine learning methods* and *deep learning methods* by defining deep learning as any kind of multi-layer neural network (LSTM, bi-LSTM, CNN) and machine learning as anything else (Bayes, SVM, random forest). We make this distinction because these different methods use separate software packages and modeling infrastructure; from a pragmatic point of view, it is helpful to split up the chapters this way. Some of the topics will overlap between the second and third sections as these are different approaches to the same tasks.

- **Natural language features:** How do we transform text data into a representation useful for machine learning? In these chapters, we explore the most common preprocessing steps for text, when they are helpful, and when they are not.

- **Machine learning methods:** We investigate the power of some of the simpler and more light-weight models in our arsenal.

- **Deep learning methods:** Given more time and resources, we see what is possible once we turn to neural networks. 

## Topics this book will not cover

This book serves as a thorough introduction to machine learning with text, along with detail practical examples, but there are many areas of natural language processing we do not cover. The [CRAN Task View on Natural Language Processing](https://cran.r-project.org/web/views/NaturalLanguageProcessing.html) provides details on other ways to use R for computational linguistics. Specific topics we do not cover include:

- Text generation
- Speech processing
- Machine translation
- Text-to-speech

## Who is this book for?

This book is designed to provide practical guidance and directly applicable knowledge for data scientists and analysts that want to integrate text into their modeling pipelines. 

We assume that the reader is somewhat familiar with R, machine learning concepts, and the [tidyverse](https://www.tidyverse.org/) family of packages. For users who don't have this background, we recommend books such as [*R for Data Science*](http://r4ds.had.co.nz/). We don't assume an extensive background in text analysis, but [*Text Mining with R*](https://www.tidytextmining.com/), by one of the authors (JS) and David Robinson, provides helpful skills in exploratory data analysis for text that will promote successful text modeling.

This book is more advanced than *Text Mining with R* and will help practitioners use their text data in more sophisticated ways.

## Code

All the code used to generate this book, including the examples, is available in our [public GitHub repository](https://github.com/EmilHvitfeldt/tidy-nlp-in-R-book).  

The end of this book contains a software bibliography with descriptions of the software and packages being used; please refer to it for details on all software used. Each chapter or section will start by loading the packages used there.

## Acknowledgements

We are so thankful for the contributions, help, and perspectives of people who have supported us in this project. There are several we would like to thank in particular.

We would like to thank David Robinson for his collaboration on the [tidytext](https://github.com/juliasilge/tidytext) package, ...

This book was written in the open, and several people contributed via pull requests or issues. Special thanks goes to those who contributed via GitHub:
