# Regression

What is regression.
How is it different then classification.
Defining what to regress on. Does it generalize

## First attempt

first attempt and full game will use same data. 
First attempt might use a subset of the data to make the example easier to understand.
and properly to give balanced dataset, which then later can be explored.

### Look at the data

### Modeling

### Evaluation

Closely examine high performaing samples and low performance sampling. 

## Different types of models

(Not all of these models are good, but are used to show strenghs and weaknessed)
- SVM
- Naive Bayes
- glmnet
- Random forrest
- knn
- NULL model

## Case study: varying n-grams & stop words

Use different n of grams, combined with different ways of removing stopwords.

## Case study: Adding custom feature

a custom feature is something that we can easily count and add to our model that isn't part of simple BoW.
https://github.com/mkearney/textfeatures
examples include: number of urls

## What evaluation metrics are appropiate

Data will most likely be sparse when using BoW

## Full game

### Feature selection

### Splitting the data

### Specifying models

### Cross-validation

### Evaluation

